name: Android UI Tests with Allure

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Install Appium
        run: |
          npm install -g appium@3.0.2
          appium driver install uiautomator2

      - name: Set up Android SDK path
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Copy APK
        run: |
          echo "📦 Checking for General-Store.apk..."
          if [ -f "$PWD/General-Store.apk" ]; then
            cp "$PWD/General-Store.apk" "/tmp/General-Store.apk"
            chmod 644 "/tmp/General-Store.apk"
            echo "APK_PATH=/tmp/General-Store.apk" >> $GITHUB_ENV
          else
            echo "❌ APK not found!"
            exit 1
          fi

      - name: Move APK to tmp for Appium
        run: |
          [ -f "$PWD/General-Store.apk" ] && echo "✅ Found APK" && cp "$PWD/General-Store.apk" "/tmp/General-Store.apk" && chmod 644 "/tmp/General-Store.apk" && echo "APK_PATH=/tmp/General-Store.apk" >> $GITHUB_ENV || (echo "❌ APK not found" && exit 1)

      - name: Start Android emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          disable-animations: true
          script: bash -c '[ -n "$CI" ] || export CI=true; echo "🕓 Booting emulator..."; timeout=300; counter=0; while [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d "\r")" != "1" ]; do [ $counter -ge $timeout ] && echo "❌ Timeout waiting for emulator to boot" && exit 1; echo "Waiting for emulator to boot... ($counter/$timeout)"; sleep 5; counter=$((counter + 5)); done; adb shell input keyevent 82; echo "✅ Emulator ready!"; adb devices; echo "📸 Starting Appium server..."; appium --base-path /wd/hub --log-level info > appium.log 2>&1 & APPIUM_PID=$!; echo "Waiting for Appium to start..."; for i in {1..30}; do curl -s http://localhost:4723/wd/hub/status > /dev/null && echo "✅ Appium server is ready!" && break; echo "Waiting for Appium... attempt $i/30"; sleep 2; done; echo "🧪 Running Maven tests..."; mvn -B clean test -Dsurefire.useFile=false -Dallure.results.directory=target/allure-results || TEST_EXIT_CODE=$?; echo "🧹 Stopping Appium..."; [ -n "$APPIUM_PID" ] && kill $APPIUM_PID 2>/dev/null || true; [ -f appium.log ] && echo "📋 Appium logs (last 50 lines):" && tail -50 appium.log; if [ -d "target/allure-results" ]; then echo "✅ Test results found in target/allure-results" && ls -la target/allure-results/; else echo "⚠️ No test results found in target/allure-results" && mkdir -p target/allure-results && echo "{}" > target/allure-results/dummy.json; fi; exit ${TEST_EXIT_CODE:-0}'

      - name: Generate Allure report
        if: always()
        run: '[ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ] && echo "📊 Generating Allure report..." && rm -rf target/site/allure-maven-plugin || true && mvn -B allure:report || (echo "⚠️ No test results to generate report from" && mkdir -p target/site/allure-maven-plugin && echo "<html><body><h1>No test results available</h1></body></html>" > target/site/allure-maven-plugin/index.html)'

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
          if-no-files-found: warn

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            appium.log
            target/surefire-reports/
          if-no-files-found: ignore
