name: Android UI Tests

on:
  push:
  pull_request:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Appium
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2

      - name: Start Appium Server
        run: |
          nohup appium --base-path /wd/hub > appium.log 2>&1 &

      - name: Create and start Android emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"
          nohup emulator -avd test -no-snapshot -noaudio -no-window &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run Tests
        env:
          APK_PATH: ${{ github.workspace }}/General-Store.apk
        run: |
          mvn clean test -Dsurefire.useFile=false
