name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android-tests:
    runs-on: macos-latest

    env:
      JAVA_HOME: /Users/runner/Library/Java/JavaVirtualMachines/adoptopenjdk-17.jdk/Contents/Home
      ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
      APK_PATH: ${{ github.workspace }}/app/General-Store.apk
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify APK exists
        run: |
          if [ ! -f "$APK_PATH" ]; then
            echo "❌ APK not found at $APK_PATH"
            exit 1
          fi
          echo "✅ APK found at $APK_PATH"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: "33"       # змінити під потрібну версію
          target: "android-33"
          arch: "x86_64"

      - name: Create and start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          emulator-name: ci-emulator
          force-avd-creation: true
          disable-animations: true
          script: |
            echo "⏳ Waiting 10 seconds for emulator to stabilize..."
            sleep 10
            echo "🌐 Starting Maven tests..."
            mvn -B clean test -Dsurefire.useFile=false -Dallure.results.directory=target/allure-results
