name: Android CI with Appium

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: '36.1.0'

    - name: Verify APK exists
      run: |
        APK_PATH="$GITHUB_WORKSPACE/app/General-Store.apk"
        if [ ! -f "$APK_PATH" ]; then
          echo "❌ APK not found at $APK_PATH"
          exit 1
        fi
        echo "✅ APK found at $APK_PATH"

    - name: Copy APK to /tmp
      run: |
        cp "$GITHUB_WORKSPACE/app/General-Store.apk" /tmp/General-Store.apk
        chmod 644 /tmp/General-Store.apk

    - name: Validate APK
      run: |
        if unzip -t /tmp/General-Store.apk >/dev/null 2>&1; then
          echo "✅ APK is a valid ZIP archive"
        else
          echo "❌ APK is corrupted"
          exit 1
        fi

    - name: Start Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: default
        arch: x86_64
        force-avd-creation: true
        emulator-options: "-no-window -no-audio"
        script: |
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb devices

    - name: Start Appium server
      run: |
        appium --base-path /wd/hub --log-level info > appium.log 2>&1 &
        echo $! > appium.pid
        # Wait until Appium server is ready
        for i in {1..30}; do
          curl -s http://localhost:4723/wd/hub/status && break
          echo "Waiting for Appium... attempt $i/30"
          sleep 2
        done

    - name: Run Maven tests
      run: |
        mvn -B clean test -Dsurefire.useFile=false -Dallure.results.directory=target/allure-results || TEST_EXIT_CODE=$?
        exit ${TEST_EXIT_CODE:-0}

    - name: Stop Appium
      if: always()
      run: |
        if [ -f appium.pid ]; then
          kill $(cat appium.pid) || true
        fi
        if [ -f appium.log ]; then
          echo "📋 Appium logs (last 50 lines):"
          tail -50 appium.log
        fi

    - name: List test results
      if: always()
      run: |
        if [ -d "target/allure-results" ]; then
          echo "✅ Test results found in target/allure-results"
          ls -la target/allure-results/
        else
          echo "⚠️ No test results found"
          mkdir -p target/allure-results
          echo "{}" > target/allure-results/dummy.json
        fi
